apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "prod"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "prod"
    spec:
      containers:
        - name: "prod"
          image: "hellorust.azurecr.io/prod"
          ports:
          - containerPort: 8000