apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "arcgitops"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "arcgitops"
    spec:
      containers:
        - name: "arcgitops"
          image: "njdkfngjkdr.azurecr.io/arcgitops"
          ports:
          - containerPort: 8000