on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n njdkfngjkdr -g njdkfngjkdr98d0-rg --location "UK South" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n njdkfngjkdr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n njdkfngjkdr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n njdkfngjkdr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: njdkfngjkdr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t njdkfngjkdr.azurecr.io/arcgitops:${{ github.sha }}
        docker push njdkfngjkdr.azurecr.io/arcgitops:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_arcgitops_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep arcgitops0c50 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace arcgitops0c50`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: arcgitops0c50
        container-registry-url: njdkfngjkdr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: arcgitopsdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: arcgitops0c50
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          njdkfngjkdr.azurecr.io/arcgitops:${{ github.sha }}
        imagepullsecrets: |
          arcgitopsdockerauth