name: Master

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build a container image for ${GITHUB_REPOSITORY}
      run: |
        docker build . -t ${ACR_URI}/rust-web-helloworld:${GITHUB_SHA}
        echo ${ACR_PASSWORD} | docker login ${ACR_URI} -u ${ACR_USERNAME} --password-stdin
        docker push ${ACR_URI}/rust-web-helloworld:${GITHUB_SHA}
      env:
        ACR_URI: ${{ secrets.ACR_URI }}
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
